// .mcp/ui-generator/tools/sync-prompt.ts
// CLI tool to sync the UI generator system prompt from markdown to JavaScript
import fs from "node:fs";
import path from "node:path";

const promptPath = path.join(
  process.cwd(),
  ".mcp",
  "ui-generator",
  "prompt.md"
);
const outputPath = path.join(
  process.cwd(),
  ".mcp",
  "ui-generator",
  "prompt.generated.mjs",
);

function main() {
  if (!fs.existsSync(promptPath)) {
    console.error(
      `[sync-mcp-prompt] Missing prompt.md at ${promptPath}`,
    );
    process.exit(1);
  }

  const content = fs.readFileSync(promptPath, "utf8");

  const file = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: pnpm sync-mcp-prompt
// Source: .mcp/ui-generator/prompt.md

export const UI_GENERATOR_SYSTEM_PROMPT = ${JSON.stringify(content)};

`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, file, "utf8");

  console.log(
    `[sync-mcp-prompt] Synced MCP system prompt to ${path.relative(
      process.cwd(),
      outputPath,
    )}`,
  );
}

main();

